
D:\Tutedude\Python\14Django>django-admin startproject Templates_in_Django_14_5

D:\Tutedude\Python\14Django>cd Templates_in_Django_14_5

D:\Tutedude\Python\14Django\Templates_in_Django_14_5>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK

D:\Tutedude\Python\14Django\Templates_in_Django_14_5>python manage.py startapp template

D:\Tutedude\Python\14Django\Templates_in_Django_14_5>python manage.py runserver
Traceback (most recent call last):
  File "D:\Tutedude\Python\14Django\Templates_in_Django_14_5\manage.py", line 22, in <module>
    main()
  File "D:\Tutedude\Python\14Django\Templates_in_Django_14_5\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 102, in __getattr__
    self._setup(name)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\django\conf\__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Tutedude\Python\14Django\Templates_in_Django_14_5\Templates_in_Django_14_5\settings.py", line 58, in <module>
    'DIRS': [os.path.join(BASE_DIR,'templates')],
NameError: name 'os' is not defined

D:\Tutedude\Python\14Django\Templates_in_Django_14_5>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 25, 2024 - 16:42:27
Django version 4.2.11, using settings 'Templates_in_Django_14_5.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Not Found: /helloworld/
[25/Apr/2024 16:42:55] "GET /helloworld/ HTTP/1.1" 404 2233
[25/Apr/2024 16:43:24] "GET /temp/ HTTP/1.1" 200 135
[25/Apr/2024 16:44:42] "GET /temp/ HTTP/1.1" 200 140